config/routes.rb
Rails.application.routes.draw do
  resources :colors
  resources :materials
  resources :orderers
  resources :orders
  resources :picked_things
  resources :things

  post 'log_in' => 'sessions#log_in'
  post 'sign_up' => 'sessions#sign_up'
  post 'log_out' => 'sessions#log_out'
  get 'sessions/log_in_form' => 'sessions#log_in_form'
  get 'sessions/sign_up_form' => 'sessions#sign_up_form'

  post 'print' => 'things#print'
  post 'pickup' => 'things#pickup'
  get 'print_form' => 'things#print_form'
  get 'pickup_form' => 'things#pickup_form'

  get 'home' => 'home#index'
  root 'home#index'

end

app/models/picked_thing.rb
class PickedThing < ActiveRecord::Base
end

app/controllers/picked_things_controller.rb
class PickedThingsController < ApplicationController
  before_action :set_picked_thing, only: [:show, :edit, :update, :destroy]

  # GET /picked_things
  # GET /picked_things.json
  def index
    @picked_things = PickedThing.all
  end

  # GET /picked_things/1
  # GET /picked_things/1.json
  def show
  end

  # GET /picked_things/new
  def new
    @picked_thing = PickedThing.new
  end

  # GET /picked_things/1/edit
  def edit
  end

  # POST /picked_things
  # POST /picked_things.json
  def create
    @picked_thing = PickedThing.new(picked_thing_params)

    respond_to do |format|
      if @picked_thing.save
        format.html { redirect_to @picked_thing, notice: 'Picked thing was successfully created.' }
        format.json { render :show, status: :created, location: @picked_thing }
      else
        format.html { render :new }
        format.json { render json: @picked_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /picked_things/1
  # PATCH/PUT /picked_things/1.json
  def update
    respond_to do |format|
      if @picked_thing.update(picked_thing_params)
        format.html { redirect_to @picked_thing, notice: 'Picked thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @picked_thing }
      else
        format.html { render :edit }
        format.json { render json: @picked_thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /picked_things/1
  # DELETE /picked_things/1.json
  def destroy
    @picked_thing.destroy
    respond_to do |format|
      format.html { redirect_to picked_things_url, notice: 'Picked thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picked_thing
      @picked_thing = PickedThing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picked_thing_params
      params.require(:picked_thing).permit(:user_id, :thing_id)
    end
end

app/helpers/picked_things_helper.rb
module PickedThingsHelper
end

app/views/picked_things/_form.html.erb
<%= form_for(@picked_thing) do |f| %>
  <% if @picked_thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picked_thing.errors.count, "error") %> prohibited this picked_thing from being saved:</h2>

      <ul>
      <% @picked_thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :thing_id %><br>
    <%= f.number_field :thing_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/picked_things/edit.html.erb
<h1>Editing Picked Thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @picked_thing %> |
<%= link_to 'Back', picked_things_path %>

app/views/picked_things/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Picked Things</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Thing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @picked_things.each do |picked_thing| %>
      <tr>
        <td><%= picked_thing.user_id %></td>
        <td><%= picked_thing.thing_id %></td>
        <td><%= link_to 'Show', picked_thing %></td>
        <td><%= link_to 'Edit', edit_picked_thing_path(picked_thing) %></td>
        <td><%= link_to 'Destroy', picked_thing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Picked thing', new_picked_thing_path %>

app/views/picked_things/new.html.erb
<h1>New Picked Thing</h1>

<%= render 'form' %>

<%= link_to 'Back', picked_things_path %>

app/views/picked_things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @picked_thing.user_id %>
</p>

<p>
  <strong>Thing:</strong>
  <%= @picked_thing.thing_id %>
</p>

<%= link_to 'Edit', edit_picked_thing_path(@picked_thing) %> |
<%= link_to 'Back', picked_things_path %>