config/routes.rb
Rails.application.routes.draw do
  resources :colors
  resources :materials
  resources :orderers
  resources :orders
  resources :picked_things
  resources :things

  post 'log_in' => 'sessions#log_in'
  post 'sign_up' => 'sessions#sign_up'
  post 'log_out' => 'sessions#log_out'
  get 'sessions/log_in_form' => 'sessions#log_in_form'
  get 'sessions/sign_up_form' => 'sessions#sign_up_form'

  post 'print' => 'things#print'
  post 'pickup' => 'things#pickup'
  get 'print_form' => 'things#print_form'
  get 'pickup_form' => 'things#pickup_form'

  get 'home' => 'home#index'
  root 'home#index'

end

app/models/thing.rb
class Thing < ActiveRecord::Base
  has_many :print_logs
  has_many :pickup_logs
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_action :set_thing, only: [:show, :edit, :update, :destroy]

  # GET /things
  # GET /things.json
  def index
    @things = Thing.all
  end

  # GET /things/1
  # GET /things/1.json
  def show
  end

  # GET /things/new
  def new
    @thing = Thing.new
  end

  # GET /things/1/edit
  def edit
  end

  # POST /things
  # POST /things.json
  def create
    @thing = Thing.new(thing_params)

    respond_to do |format|
      if @thing.save
        format.html { redirect_to @thing, notice: 'Thing was successfully created.' }
        format.json { render :show, status: :created, location: @thing }
      else
        format.html { render :new }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /things/1
  # PATCH/PUT /things/1.json
  def update
    respond_to do |format|
      if @thing.update(thing_params)
        format.html { redirect_to @thing, notice: 'Thing was successfully updated.' }
        format.json { render :show, status: :ok, location: @thing }
      else
        format.html { render :edit }
        format.json { render json: @thing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.json
  def destroy
    @thing.destroy
    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pickup

    @thing = get_thing_by_name params[:thing_name]

    @thing.ready_for_pickup_amount -= params[:amount].to_i
    @thing.save

    @pickup_log = PickupLog.new
    @pickup_log.user_id = current_user.id
    @pickup_log.thing_id = @thing.id
    @pickup_log.amount = params[:amount].to_i
    @pickup_log.save

    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  def print

    @thing = get_thing_by_name params[:thing_name]

    @thing.ready_for_pickup_amount += params[:amount].to_i
    @thing.save

    @print_log = PrintLog.new
    @print_log.user_id = current_user.id
    @print_log.thing_id = @thing.id
    @print_log.amount = params[:amount].to_i
    @print_log.save

    respond_to do |format|
      format.html { redirect_to things_url, notice: 'Thing was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  def print_form
  end

  def pickup_form
  end

  private
    def get_thing_by_name name
      @thing = Thing.find_by_name(name)
      if !@thing
        @thing = Thing.new
        @thing.name = name
        @thing.ready_for_pickup_amount = 0
        @thing.save
      end
      return @thing
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_thing
      @thing = Thing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thing_params
      params.require(:thing).permit(:name, :ready_for_pickup_amount)
    end
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ready_for_pickup_amount %><br>
    <%= f.number_field :ready_for_pickup_amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/things/edit.html.erb
<h1>Editing Thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Things</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ready for pickup</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= thing.name %></td>
        <td><%= thing.ready_for_pickup_amount %></td>
<!--
        <td><%= link_to 'Show', thing %></td>
        <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
        <td><%= link_to 'Destroy', thing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Thing', new_thing_path %>

app/views/things/new.html.erb
<h1>New Thing</h1>

<%= render 'form' %>

<%= link_to 'Back', things_path %>

app/views/things/pickup_form.html.erb
<div class="col s12">

  <form action="/pickup" accept-charset="UTF-8" method="post" autocomplete="false">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <h2>Pickup notification</h2>

    <div class="input-field col s12">
      <input name="thing_name" type="text" id="autocomplete-input" class="thing" autocomplete="off">
      <label for="autocomplete-input">Thing name</label>
    </div>

    <div class="input-field col s12">
      <input name="amount" type="text" id="autocomplete-input" autocomplete="off">
      <label for="autocomplete-input">Amount</label>
    </div>

    <button type="submit">Submit</button>
  </form>

</div>


<script>
  $(document).ready(function() {
    $('input.thing').autocomplete({
      data: {
        <% Thing.all.each do |thing| %>
          "<%= thing.name %>": null,
        <% end %>
      }
    });
  });
</script>

app/views/things/print_form.html.erb
<div class="col s12">

  <form action="/print" accept-charset="UTF-8" method="post" autocomplete="false">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <h2>Print notification</h2>

    <div class="input-field col s12">
      <input name="thing_name" type="text" id="autocomplete-input" class="thing" autocomplete="off">
      <label for="autocomplete-input">Thing name</label>
    </div>

    <div class="input-field col s12">
      <input name="amount" type="text" id="autocomplete-input" autocomplete="off">
      <label for="autocomplete-input">Amount</label>
    </div>

    <button type="submit">Submit</button>
  </form>

</div>


<script>
  $(document).ready(function() {
    $('input.thing').autocomplete({
      data: {
        <% Thing.all.each do |thing| %>
          "<%= thing.name %>": null,
        <% end %>
      }
    });
  });
</script>

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @thing.name %>
</p>

<p>
  <strong>Ready for pickup amount:</strong>
  <%= @thing.ready_for_pickup_amount %>
</p>

<%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', things_path %>