config/routes.rb
Rails.application.routes.draw do
  resources :colors
  resources :materials
  resources :orderers
  resources :orders
  resources :picked_things
  resources :things

  post 'log_in' => 'sessions#log_in'
  post 'sign_up' => 'sessions#sign_up'
  post 'log_out' => 'sessions#log_out'
  get 'sessions/log_in_form' => 'sessions#log_in_form'
  get 'sessions/sign_up_form' => 'sessions#sign_up_form'

  post 'print' => 'things#print'
  post 'pickup' => 'things#pickup'
  get 'print_form' => 'things#print_form'
  get 'pickup_form' => 'things#pickup_form'

  get 'home' => 'home#index'
  root 'home#index'

end

app/models/material.rb
class Material < ActiveRecord::Base
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:name, :color_id, :in_stock)
    end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/materials/_form.html.erb
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color_id %><br>
    <%= f.number_field :color_id %>
  </div>
  <div class="field">
    <%= f.label :in_stock %><br>
    <%= f.check_box :in_stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing Material</h1>

<%= render 'form' %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Materials</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th>In stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.name %></td>
        <td><%= material.color_id %></td>
        <td><%= material.in_stock %></td>
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material', new_material_path %>

app/views/materials/new.html.erb
<h1>New Material</h1>

<%= render 'form' %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @material.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @material.color_id %>
</p>

<p>
  <strong>In stock:</strong>
  <%= @material.in_stock %>
</p>

<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>